config/routes.rb
Rails.application.routes.draw do
  resources :quizzes

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :quiz

	validates :text, presence: true
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	#
	validates :subject, presence: true
	#
	validates :question, presence: true
	# il quiz ha tante risposte
	has_many :answers
	# è possibile modificare le risposte sulla stessa pagina
	accepts_nested_attributes_for :answers

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new

    3.times do
      @quiz.answers.build
    end
    #al quiz è collegato un insieme di risposte associando anche i'id
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      
      
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Il quiz è stato creato con successo.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Il quiz è stato aggiornato con successo..' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Il quiz è stato eliminato con successo.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:subject, :question, :image, answers_attributes: [:id, :text, :correct])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizzly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="header">
		<div class="container">	
			<%= image_tag "logo0.png" %>
		</div>
	</div>	
	<div class="container">			
		<%= yield %>
	</div>

	
</body>
</html>

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>

  <%= f.fields_for :answers do |answer_form| %>
    <div>
        <%= answer_form.label 'Testo:' %>
        <%= answer_form.text_field :text %>

        <%= answer_form.label 'Corretto?' %>
        <%= answer_form.check_box :correct%>
      
    </div>
    <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Modificare il quiz</h1>

<%= render 'form' %>

<%= link_to 'Mostra', @quiz %> |
<%= link_to 'Indietro', quizzes_path %>

app/views/quizzes/index.html.erb
<h1>Elenco dei quiz</h1>

<table>
  <thead>
    <tr>
      <th>Argomento</th>
      <th>Domanda</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.subject %></td>
        <td><%= quiz.question %></td>
        <td><%= link_to 'Mostra', quiz %></td>
        <td><%= link_to 'Modifica', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Elimina', quiz, method: :delete, data: { confirm: 'Sei sicuro di voler eliminare?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuovo Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render 'form' %>

<%= link_to 'Indietro', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Argomento:</strong>
  <%= @quiz.subject %>
</p>

<p>
  <strong>Domanda:</strong>
  <%= @quiz.question %>
</p>


<!-- <img src="<%= @quiz.image%>">  -->
   <%= image_tag  @quiz.image, size: "250x250" %>


 <p>
  <strong>Risposte:</strong>
  
<ul>
	<% @quiz.answers.each do |a| %>
     	<li>
        	<%= a.text %>
        	<% if a.correct? %>
        		(risposta corretta)
          <% else %>
            (risposta errata)
        	<% end %>
      	</li>
  <% end %>
</ul>
</p>

<%= link_to 'Modifica', edit_quiz_path(@quiz) %> |
<%= link_to 'Indietro', quizzes_path %>